import type { Locale } from '@/lib/i18n';

export type PartnerContentText = {
  consentAction: string;
  changeChoice: string;
  dialogTitle: string;
  dialogBody: string;
  dialogDetail: string;
  allowGame: string;
  keepBlocked: string;
  close: string;
  blockedNotice: string;
  privacyChoices: string;
};

const messages: Record<Locale, PartnerContentText> = {
  en: { consentAction: 'Choose optional content settings', changeChoice: 'Change optional content settings', dialogTitle: 'Allow this GR8 Select game?', dialogBody: 'This game is delivered by an external game service. Loading it may let that service process device, usage and advertising data under its own terms.', dialogDetail: 'This choice controls external GR8 Select games on this device. It does not change your Google privacy choices.', allowGame: 'Allow and play', keepBlocked: 'Keep blocked', close: 'Close', blockedNotice: 'External game content stays blocked until you choose to allow it.', privacyChoices: 'Privacy Choices' },
  es: { consentAction: 'Elegir contenido opcional', changeChoice: 'Cambiar contenido opcional', dialogTitle: '¿Permitir este juego de GR8 Select?', dialogBody: 'Este juego lo ofrece un servicio externo. Al cargarlo, ese servicio puede tratar datos del dispositivo, uso y publicidad según sus condiciones.', dialogDetail: 'Esta elección controla los juegos externos de GR8 Select en este dispositivo. No cambia tus opciones de privacidad de Google.', allowGame: 'Permitir y jugar', keepBlocked: 'Mantener bloqueado', close: 'Cerrar', blockedNotice: 'El contenido externo permanece bloqueado hasta que decidas permitirlo.', privacyChoices: 'Opciones de privacidad' },
  'pt-BR': { consentAction: 'Escolher conteúdo opcional', changeChoice: 'Alterar conteúdo opcional', dialogTitle: 'Permitir este jogo GR8 Select?', dialogBody: 'Este jogo é fornecido por um serviço externo. Ao carregá-lo, esse serviço pode processar dados do dispositivo, uso e publicidade conforme seus termos.', dialogDetail: 'Esta escolha controla jogos externos GR8 Select neste dispositivo. Ela não altera suas escolhas de privacidade do Google.', allowGame: 'Permitir e jogar', keepBlocked: 'Manter bloqueado', close: 'Fechar', blockedNotice: 'O conteúdo externo fica bloqueado até você permitir.', privacyChoices: 'Opções de privacidade' },
  fr: { consentAction: 'Choisir le contenu facultatif', changeChoice: 'Modifier le contenu facultatif', dialogTitle: 'Autoriser ce jeu GR8 Select ?', dialogBody: 'Ce jeu est fourni par un service externe. Son chargement peut permettre à ce service de traiter des données d’appareil, d’utilisation et de publicité selon ses propres conditions.', dialogDetail: 'Ce choix contrôle les jeux GR8 Select externes sur cet appareil. Il ne modifie pas vos choix de confidentialité Google.', allowGame: 'Autoriser et jouer', keepBlocked: 'Garder bloqué', close: 'Fermer', blockedNotice: 'Le contenu externe reste bloqué tant que vous ne l’autorisez pas.', privacyChoices: 'Choix de confidentialité' },
  de: { consentAction: 'Optionale Inhalte auswählen', changeChoice: 'Optionale Inhalte ändern', dialogTitle: 'Dieses GR8 Select Spiel erlauben?', dialogBody: 'Dieses Spiel wird von einem externen Spieledienst bereitgestellt. Beim Laden kann dieser Dienst Geräte-, Nutzungs- und Werbedaten nach eigenen Bedingungen verarbeiten.', dialogDetail: 'Diese Auswahl steuert externe GR8 Select Spiele auf diesem Gerät. Deine Google-Datenschutzauswahl bleibt unverändert.', allowGame: 'Erlauben und spielen', keepBlocked: 'Blockiert lassen', close: 'Schließen', blockedNotice: 'Externe Spielinhalte bleiben blockiert, bis du sie erlaubst.', privacyChoices: 'Datenschutzoptionen' },
  it: { consentAction: 'Scegli contenuti opzionali', changeChoice: 'Modifica contenuti opzionali', dialogTitle: 'Consentire questo gioco GR8 Select?', dialogBody: 'Questo gioco è fornito da un servizio esterno. Caricandolo, il servizio può trattare dati del dispositivo, di utilizzo e pubblicitari secondo i propri termini.', dialogDetail: 'Questa scelta controlla i giochi GR8 Select esterni su questo dispositivo. Non modifica le scelte privacy di Google.', allowGame: 'Consenti e gioca', keepBlocked: 'Mantieni bloccato', close: 'Chiudi', blockedNotice: 'Il contenuto esterno resta bloccato finché non lo consenti.', privacyChoices: 'Scelte privacy' },
  pl: { consentAction: 'Wybierz treści opcjonalne', changeChoice: 'Zmień treści opcjonalne', dialogTitle: 'Zezwolić na tę grę GR8 Select?', dialogBody: 'Gra jest dostarczana przez zewnętrzną usługę. Jej uruchomienie może pozwolić tej usłudze przetwarzać dane urządzenia, użycia i reklam zgodnie z własnymi warunkami.', dialogDetail: 'Ten wybór steruje zewnętrznymi grami GR8 Select na tym urządzeniu. Nie zmienia ustawień prywatności Google.', allowGame: 'Zezwól i graj', keepBlocked: 'Pozostaw zablokowane', close: 'Zamknij', blockedNotice: 'Zewnętrzna treść gry pozostaje zablokowana do czasu udzielenia zgody.', privacyChoices: 'Ustawienia prywatności' },
  tr: { consentAction: 'İsteğe bağlı içeriği seç', changeChoice: 'İsteğe bağlı içeriği değiştir', dialogTitle: 'Bu GR8 Select oyununa izin verilsin mi?', dialogBody: 'Bu oyun harici bir oyun hizmeti tarafından sunulur. Yüklendiğinde hizmet, cihaz, kullanım ve reklam verilerini kendi şartlarına göre işleyebilir.', dialogDetail: 'Bu seçim bu cihazdaki harici GR8 Select oyunlarını kontrol eder. Google gizlilik seçimlerinizi değiştirmez.', allowGame: 'İzin ver ve oyna', keepBlocked: 'Engelli tut', close: 'Kapat', blockedNotice: 'İzin verene kadar harici oyun içeriği engelli kalır.', privacyChoices: 'Gizlilik seçenekleri' },
  id: { consentAction: 'Pilih konten opsional', changeChoice: 'Ubah konten opsional', dialogTitle: 'Izinkan game GR8 Select ini?', dialogBody: 'Game ini disediakan oleh layanan game eksternal. Saat dimuat, layanan tersebut dapat memproses data perangkat, penggunaan, dan iklan menurut ketentuannya.', dialogDetail: 'Pilihan ini mengatur game GR8 Select eksternal di perangkat ini. Pilihan privasi Google tidak berubah.', allowGame: 'Izinkan dan mainkan', keepBlocked: 'Tetap blokir', close: 'Tutup', blockedNotice: 'Konten game eksternal tetap diblokir sampai Anda mengizinkannya.', privacyChoices: 'Pilihan privasi' },
  ja: { consentAction: '任意コンテンツを設定', changeChoice: '任意コンテンツの設定を変更', dialogTitle: 'この GR8 Select ゲームを許可しますか？', dialogBody: 'このゲームは外部のゲームサービスから提供されます。読み込むと、そのサービスが独自の規約に基づいて端末、利用状況、広告データを処理する場合があります。', dialogDetail: 'この設定は、この端末の外部 GR8 Select ゲームだけを制御します。Google のプライバシー設定は変更されません。', allowGame: '許可してプレイ', keepBlocked: 'ブロックを続ける', close: '閉じる', blockedNotice: '許可するまで外部ゲームコンテンツはブロックされます。', privacyChoices: 'プライバシー設定' },
  ko: { consentAction: '선택 콘텐츠 설정', changeChoice: '선택 콘텐츠 설정 변경', dialogTitle: '이 GR8 Select 게임을 허용할까요?', dialogBody: '이 게임은 외부 게임 서비스에서 제공됩니다. 로드하면 해당 서비스가 자체 약관에 따라 기기, 사용 및 광고 데이터를 처리할 수 있습니다.', dialogDetail: '이 선택은 이 기기의 외부 GR8 Select 게임만 제어합니다. Google 개인정보 선택은 변경되지 않습니다.', allowGame: '허용하고 플레이', keepBlocked: '차단 유지', close: '닫기', blockedNotice: '허용하기 전까지 외부 게임 콘텐츠는 차단됩니다.', privacyChoices: '개인정보 선택' },
  hi: { consentAction: 'वैकल्पिक सामग्री चुनें', changeChoice: 'वैकल्पिक सामग्री बदलें', dialogTitle: 'इस GR8 Select गेम को अनुमति दें?', dialogBody: 'यह गेम एक बाहरी गेम सेवा देती है। इसे लोड करने पर वह सेवा अपनी शर्तों के अनुसार डिवाइस, उपयोग और विज्ञापन डेटा संसाधित कर सकती है।', dialogDetail: 'यह विकल्प इस डिवाइस पर बाहरी GR8 Select गेम को नियंत्रित करता है। इससे Google की गोपनीयता पसंद नहीं बदलती।', allowGame: 'अनुमति दें और खेलें', keepBlocked: 'ब्लॉक रखें', close: 'बंद करें', blockedNotice: 'अनुमति देने तक बाहरी गेम सामग्री ब्लॉक रहती है।', privacyChoices: 'गोपनीयता विकल्प' },
  ar: { consentAction: 'اختيار المحتوى الاختياري', changeChoice: 'تغيير المحتوى الاختياري', dialogTitle: 'هل تسمح بلعبة GR8 Select هذه؟', dialogBody: 'تقدم هذه اللعبة خدمة ألعاب خارجية. عند تحميلها قد تعالج الخدمة بيانات الجهاز والاستخدام والإعلانات وفق شروطها.', dialogDetail: 'يتحكم هذا الخيار في ألعاب GR8 Select الخارجية على هذا الجهاز فقط، ولا يغير خيارات خصوصية Google.', allowGame: 'السماح واللعب', keepBlocked: 'إبقاء الحظر', close: 'إغلاق', blockedNotice: 'يبقى محتوى اللعبة الخارجي محظوراً حتى تسمح به.', privacyChoices: 'خيارات الخصوصية' }
};

export function partnerContentText(locale: Locale): PartnerContentText {
  return messages[locale] || messages.en;
}
