import type { Locale } from '@/lib/i18n';

export type PartnerContentText = {
  consentAction: string;
  changeChoice: string;
  dialogTitle: string;
  dialogBody: string;
  dialogDetail: string;
  allowGame: string;
  keepBlocked: string;
  close: string;
  blockedNotice: string;
  privacyChoices: string;
  providerPrivacy: string;
};

const messages: Record<Locale, PartnerContentText> = {
  en: { consentAction: 'Choose external content settings', changeChoice: 'Change external content settings', dialogTitle: 'Allow this GR8 Select game?', dialogBody: 'This game is supplied by GameMonetize and includes advertising controlled by GameMonetize. If you load it, GameMonetize may process device, usage and advertising data under its own terms.', dialogDetail: 'This choice controls GameMonetize content on this device. It does not change your Google privacy choices or give GR8 GAMZ control over consent inside the game.', allowGame: 'Allow content and play', keepBlocked: 'Keep blocked', close: 'Close', blockedNotice: 'GameMonetize game and advertising content stays blocked until you choose to allow it.', privacyChoices: 'Privacy Choices', providerPrivacy: 'Read the GameMonetize privacy policy' },
  es: { consentAction: 'Elegir contenido externo', changeChoice: 'Cambiar contenido externo', dialogTitle: '¿Permitir este juego de GR8 Select?', dialogBody: 'GameMonetize proporciona este juego e incluye publicidad controlada por GameMonetize. Si lo cargas, GameMonetize puede tratar datos del dispositivo, uso y publicidad según sus propias condiciones.', dialogDetail: 'Esta elección controla el contenido de GameMonetize en este dispositivo. No cambia tus opciones de privacidad de Google ni da a GR8 GAMZ control sobre el consentimiento dentro del juego.', allowGame: 'Permitir contenido y jugar', keepBlocked: 'Mantener bloqueado', close: 'Cerrar', blockedNotice: 'El juego y la publicidad de GameMonetize permanecen bloqueados hasta que decidas permitirlos.', privacyChoices: 'Opciones de privacidad', providerPrivacy: 'Leer la política de privacidad de GameMonetize' },
  'pt-BR': { consentAction: 'Escolher conteúdo externo', changeChoice: 'Alterar conteúdo externo', dialogTitle: 'Permitir este jogo GR8 Select?', dialogBody: 'Este jogo é fornecido pela GameMonetize e inclui publicidade controlada pela GameMonetize. Ao carregá-lo, a GameMonetize pode processar dados do dispositivo, uso e publicidade conforme seus próprios termos.', dialogDetail: 'Esta escolha controla o conteúdo da GameMonetize neste dispositivo. Ela não altera suas escolhas de privacidade do Google nem dá à GR8 GAMZ controle sobre o consentimento dentro do jogo.', allowGame: 'Permitir conteúdo e jogar', keepBlocked: 'Manter bloqueado', close: 'Fechar', blockedNotice: 'O jogo e o conteúdo publicitário da GameMonetize ficam bloqueados até você permitir.', privacyChoices: 'Opções de privacidade', providerPrivacy: 'Ler a política de privacidade da GameMonetize' },
  fr: { consentAction: 'Choisir le contenu externe', changeChoice: 'Modifier le contenu externe', dialogTitle: 'Autoriser ce jeu GR8 Select ?', dialogBody: 'Ce jeu est fourni par GameMonetize et inclut de la publicité contrôlée par GameMonetize. Si vous le chargez, GameMonetize peut traiter des données relatives à l’appareil, à l’utilisation et à la publicité selon ses propres conditions.', dialogDetail: 'Ce choix contrôle le contenu GameMonetize sur cet appareil. Il ne modifie pas vos choix de confidentialité Google et ne donne pas à GR8 GAMZ le contrôle du consentement dans le jeu.', allowGame: 'Autoriser le contenu et jouer', keepBlocked: 'Garder bloqué', close: 'Fermer', blockedNotice: 'Le jeu et le contenu publicitaire GameMonetize restent bloqués jusqu’à votre autorisation.', privacyChoices: 'Choix de confidentialité', providerPrivacy: 'Lire la politique de confidentialité de GameMonetize' },
  de: { consentAction: 'Externe Inhalte auswählen', changeChoice: 'Externe Inhalte ändern', dialogTitle: 'Dieses GR8 Select Spiel erlauben?', dialogBody: 'Dieses Spiel wird von GameMonetize bereitgestellt und enthält von GameMonetize gesteuerte Werbung. Beim Laden kann GameMonetize Geräte-, Nutzungs- und Werbedaten nach eigenen Bedingungen verarbeiten.', dialogDetail: 'Diese Auswahl steuert GameMonetize-Inhalte auf diesem Gerät. Sie ändert deine Google-Datenschutzauswahl nicht und gibt GR8 GAMZ keine Kontrolle über die Einwilligung im Spiel.', allowGame: 'Inhalte erlauben und spielen', keepBlocked: 'Blockiert lassen', close: 'Schließen', blockedNotice: 'Spiel- und Werbeinhalte von GameMonetize bleiben blockiert, bis du sie erlaubst.', privacyChoices: 'Datenschutzoptionen', providerPrivacy: 'GameMonetize-Datenschutzrichtlinie lesen' },
  it: { consentAction: 'Scegli contenuti esterni', changeChoice: 'Modifica contenuti esterni', dialogTitle: 'Consentire questo gioco GR8 Select?', dialogBody: 'Questo gioco è fornito da GameMonetize e include pubblicità controllata da GameMonetize. Caricandolo, GameMonetize può trattare dati del dispositivo, di utilizzo e pubblicitari secondo i propri termini.', dialogDetail: 'Questa scelta controlla i contenuti GameMonetize su questo dispositivo. Non modifica le scelte privacy di Google e non dà a GR8 GAMZ il controllo del consenso all’interno del gioco.', allowGame: 'Consenti contenuti e gioca', keepBlocked: 'Mantieni bloccato', close: 'Chiudi', blockedNotice: 'Il gioco e i contenuti pubblicitari GameMonetize restano bloccati finché non li consenti.', privacyChoices: 'Scelte privacy', providerPrivacy: 'Leggi l’informativa sulla privacy di GameMonetize' },
  pl: { consentAction: 'Wybierz treści zewnętrzne', changeChoice: 'Zmień treści zewnętrzne', dialogTitle: 'Zezwolić na tę grę GR8 Select?', dialogBody: 'Ta gra jest dostarczana przez GameMonetize i zawiera reklamy kontrolowane przez GameMonetize. Po jej uruchomieniu GameMonetize może przetwarzać dane urządzenia, użytkowania i reklam zgodnie z własnymi warunkami.', dialogDetail: 'Ten wybór steruje treściami GameMonetize na tym urządzeniu. Nie zmienia ustawień prywatności Google ani nie daje GR8 GAMZ kontroli nad zgodą wewnątrz gry.', allowGame: 'Zezwól na treści i graj', keepBlocked: 'Pozostaw zablokowane', close: 'Zamknij', blockedNotice: 'Gra i treści reklamowe GameMonetize pozostają zablokowane do czasu udzielenia zgody.', privacyChoices: 'Ustawienia prywatności', providerPrivacy: 'Przeczytaj politykę prywatności GameMonetize' },
  tr: { consentAction: 'Harici içerik ayarlarını seç', changeChoice: 'Harici içerik ayarlarını değiştir', dialogTitle: 'Bu GR8 Select oyununa izin verilsin mi?', dialogBody: 'Bu oyun GameMonetize tarafından sunulur ve GameMonetize tarafından kontrol edilen reklamlar içerir. Yüklerseniz GameMonetize, cihaz, kullanım ve reklam verilerini kendi şartlarına göre işleyebilir.', dialogDetail: 'Bu seçim bu cihazdaki GameMonetize içeriğini kontrol eder. Google gizlilik seçimlerinizi değiştirmez ve GR8 GAMZ’e oyun içindeki izin üzerinde kontrol vermez.', allowGame: 'İçeriğe izin ver ve oyna', keepBlocked: 'Engelli tut', close: 'Kapat', blockedNotice: 'GameMonetize oyun ve reklam içeriği siz izin verene kadar engelli kalır.', privacyChoices: 'Gizlilik seçenekleri', providerPrivacy: 'GameMonetize gizlilik politikasını okuyun' },
  id: { consentAction: 'Pilih konten eksternal', changeChoice: 'Ubah konten eksternal', dialogTitle: 'Izinkan game GR8 Select ini?', dialogBody: 'Game ini disediakan oleh GameMonetize dan berisi iklan yang dikendalikan oleh GameMonetize. Jika dimuat, GameMonetize dapat memproses data perangkat, penggunaan, dan iklan menurut ketentuannya sendiri.', dialogDetail: 'Pilihan ini mengatur konten GameMonetize di perangkat ini. Pilihan privasi Google tidak berubah dan GR8 GAMZ tidak mendapat kendali atas persetujuan di dalam game.', allowGame: 'Izinkan konten dan mainkan', keepBlocked: 'Tetap blokir', close: 'Tutup', blockedNotice: 'Konten game dan iklan GameMonetize tetap diblokir sampai Anda mengizinkannya.', privacyChoices: 'Pilihan privasi', providerPrivacy: 'Baca kebijakan privasi GameMonetize' },
  ja: { consentAction: '外部コンテンツを設定', changeChoice: '外部コンテンツの設定を変更', dialogTitle: 'この GR8 Select ゲームを許可しますか？', dialogBody: 'このゲームは GameMonetize が提供し、GameMonetize が管理する広告を含みます。読み込むと、GameMonetize が独自の規約に基づいて端末、利用状況、広告データを処理する場合があります。', dialogDetail: 'この設定は、この端末の GameMonetize コンテンツだけを制御します。Google のプライバシー設定は変更されず、GR8 GAMZ がゲーム内の同意を管理することもありません。', allowGame: 'コンテンツを許可してプレイ', keepBlocked: 'ブロックを続ける', close: '閉じる', blockedNotice: '許可するまで GameMonetize のゲームと広告コンテンツはブロックされます。', privacyChoices: 'プライバシー設定', providerPrivacy: 'GameMonetize のプライバシーポリシーを読む' },
  ko: { consentAction: '외부 콘텐츠 설정', changeChoice: '외부 콘텐츠 설정 변경', dialogTitle: '이 GR8 Select 게임을 허용할까요?', dialogBody: '이 게임은 GameMonetize에서 제공하며 GameMonetize가 관리하는 광고를 포함합니다. 로드하면 GameMonetize가 자체 약관에 따라 기기, 사용 및 광고 데이터를 처리할 수 있습니다.', dialogDetail: '이 선택은 이 기기의 GameMonetize 콘텐츠만 제어합니다. Google 개인정보 선택은 변경되지 않으며 GR8 GAMZ가 게임 내부의 동의를 제어하지도 않습니다.', allowGame: '콘텐츠를 허용하고 플레이', keepBlocked: '차단 유지', close: '닫기', blockedNotice: '허용하기 전까지 GameMonetize 게임과 광고 콘텐츠는 차단됩니다.', privacyChoices: '개인정보 선택', providerPrivacy: 'GameMonetize 개인정보처리방침 읽기' },
  hi: { consentAction: 'बाहरी सामग्री चुनें', changeChoice: 'बाहरी सामग्री बदलें', dialogTitle: 'इस GR8 Select गेम को अनुमति दें?', dialogBody: 'यह गेम GameMonetize देता है और इसमें GameMonetize द्वारा नियंत्रित विज्ञापन शामिल हैं। इसे लोड करने पर GameMonetize अपनी शर्तों के अनुसार डिवाइस, उपयोग और विज्ञापन डेटा संसाधित कर सकता है।', dialogDetail: 'यह विकल्प इस डिवाइस पर GameMonetize सामग्री को नियंत्रित करता है। इससे Google की गोपनीयता पसंद नहीं बदलती और GR8 GAMZ को गेम के अंदर सहमति पर नियंत्रण नहीं मिलता।', allowGame: 'सामग्री की अनुमति दें और खेलें', keepBlocked: 'ब्लॉक रखें', close: 'बंद करें', blockedNotice: 'अनुमति देने तक GameMonetize गेम और विज्ञापन सामग्री ब्लॉक रहती है।', privacyChoices: 'गोपनीयता विकल्प', providerPrivacy: 'GameMonetize की गोपनीयता नीति पढ़ें' },
  ar: { consentAction: 'اختيار المحتوى الخارجي', changeChoice: 'تغيير المحتوى الخارجي', dialogTitle: 'هل تسمح بلعبة GR8 Select هذه؟', dialogBody: 'تقدم GameMonetize هذه اللعبة، وهي تتضمن إعلانات تتحكم بها GameMonetize. إذا حمّلتها، فقد تعالج GameMonetize بيانات الجهاز والاستخدام والإعلانات وفق شروطها الخاصة.', dialogDetail: 'يتحكم هذا الخيار في محتوى GameMonetize على هذا الجهاز. ولا يغير خيارات خصوصية Google ولا يمنح GR8 GAMZ التحكم في الموافقة داخل اللعبة.', allowGame: 'السماح بالمحتوى واللعب', keepBlocked: 'إبقاء الحظر', close: 'إغلاق', blockedNotice: 'تبقى لعبة GameMonetize ومحتواها الإعلاني محظورين حتى تسمح بهما.', privacyChoices: 'خيارات الخصوصية', providerPrivacy: 'قراءة سياسة خصوصية GameMonetize' }
};

export function partnerContentText(locale: Locale): PartnerContentText {
  return messages[locale] || messages.en;
}
