import type { Metadata } from 'next';
import GamepadTester from '@/components/tools/GamepadTester';
import ToolPageFrame from '@/components/tools/ToolPageFrame';
import { canonical } from '@/lib/features';

const title = 'Gamepad Tester - Test Controller Buttons & Stick Drift | GR8 GAMZ';
const description = 'Test a gamepad or controller online. View buttons, triggers, live analog-stick axes and centre movement using the standard browser Gamepad API.';
export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: canonical('/tools/gamepad-tester') }, robots: { index: true, follow: true } };

export default function GamepadTesterPage() {
  return <ToolPageFrame toolId="gamepad-tester" description={description} eyebrow="Controller input check" intro="Connect a controller, press one of its buttons and scan. The tester reads the standard Gamepad API to show button values and live axes without requesting an account, installing a driver or sending the controller identifier to analytics." utility={<GamepadTester />}>
    <section><h2>How can I test a controller online?</h2><p>Connect the controller by USB or Bluetooth before or after opening this page. Press a controller button, then choose Scan. Browsers often wait for a deliberate button press before revealing a gamepad to a website. When detected, the page displays the browser-provided identifier, button values, stick positions and axis readings.</p><p>Press each button and move each stick through its range. Digital buttons commonly move between zero and one, while analog triggers may report intermediate values when the browser and controller expose them. Axis layouts can vary, so compare the moving number with the physical control you are operating instead of assuming every controller uses the same mapping.</p></section>
    <section><h2>How can I check for stick drift?</h2><p>Release the sticks gently and observe their visual positions and axis values. A perfectly displayed zero is not guaranteed: small movement near the centre may indicate drift, calibration differences, deadzone handling or controller/browser behaviour. The centre-movement summary reports the largest current difference from the selected baseline, but it does not label the hardware as defective.</p><p>If the physical resting point is consistently offset, choose Set current position as baseline to compare subsequent movement with that position. This is a viewing aid and does not recalibrate the controller at operating-system or firmware level. Repeat the observation after reconnecting and use the manufacturer&apos;s supported calibration tool where available.</p></section>
    <section><h2>What is controller deadzone?</h2><p>A deadzone is a region around an analog stick&apos;s centre where small movement is ignored. Games and controller software can apply different deadzones, response curves and acceleration. The browser may report raw-looking axis movement that a game intentionally filters, so a small non-zero value here might have no effect during play.</p><p>To understand a game-specific problem, compare this page with the game&apos;s own input and deadzone settings. Change one setting at a time and avoid assuming that one number is correct for every controller.</p></section>
    <section><h2>Why isn&apos;t my controller detected?</h2><p>First press a button while the page is active. Then check the cable, wireless pairing and operating-system controller list. Some browser, device and controller combinations do not expose the Gamepad API, and remote-desktop software may not forward controller input. Closing another application that has exclusive control can also help.</p><h2>Do browser gamepad tests work with every controller?</h2><p>No. Support depends on the browser, operating system, connection and the controller&apos;s exposed mapping. A standard mapping usually produces the clearest layout, but unusual devices may still appear with different button or axis numbers.</p><h2>How do I test controller buttons?</h2><p>Press and release each control while watching the numbered button grid. A highlighted value shows what the browser currently reports. For triggers, an intermediate analog value may appear rather than only off or on.</p></section>
  </ToolPageFrame>;
}
