import type { Metadata } from 'next';
import SensitivityConverter from '@/components/tools/SensitivityConverter';
import ToolPageFrame from '@/components/tools/ToolPageFrame';
import { canonical } from '@/lib/features';

const title = 'Sensitivity Converter - Convert Mouse Sensitivity & eDPI | GR8 GAMZ';
const description = 'Calculate mouse eDPI and cm per 360, then convert sensitivity between a small set of game engines backed by published source-code constants.';
export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: canonical('/tools/sensitivity-converter') }, robots: { index: true, follow: true } };

export default function SensitivityConverterPage() {
  return <ToolPageFrame toolId="sensitivity-converter" description={description} eyebrow="Mouse setting calculator" intro="Enter a positive DPI and in-game sensitivity to calculate eDPI and estimated centimetres per 360-degree turn. Game conversion is deliberately limited to engine values supported by published source code rather than guessed constants." utility={<SensitivityConverter />}>
    <section><h2>What is mouse sensitivity?</h2><p>Mouse sensitivity controls how far the view moves in response to mouse input. Hardware DPI describes the counts reported by the mouse for physical movement, while an in-game sensitivity value applies the game&apos;s own scale. Two games can use the same number but produce different turns because their internal degrees-per-count constants differ.</p><p>This calculator keeps those parts separate. It never assumes that a sensitivity number has the same meaning in every title. The initial built-in game list is intentionally small and limited to published source-code evidence. The listed presets currently use the same default yaw scale, so a conversion between them preserves the numerical sensitivity; the eDPI and cm/360 results remain useful for comparing physical settings.</p></section>
    <section><h2>What is eDPI and how do I calculate it?</h2><p>eDPI is hardware DPI multiplied by the in-game sensitivity value. For example, 800 DPI with sensitivity 2 produces 1,600 eDPI. It is a compact way to compare settings within games that share the same sensitivity scale, but it is not a universal physical measurement across unrelated engines.</p><p>Acceleration, raw-input behaviour, operating-system settings and game-specific scaling can all affect the relationship between movement and view rotation. Use eDPI as one part of a settings record, not proof that two different games will feel identical.</p></section>
    <section><h2>What is cm/360?</h2><p>Centimetres per 360, written cm/360, estimates the physical mouse travel needed for one complete horizontal turn. The calculation uses DPI, sensitivity and the selected game&apos;s verified degrees-per-count value: 360 degrees multiplied by 2.54 centimetres per inch, divided by DPI, sensitivity and degrees per count.</p><p>A larger cm/360 means more physical travel for a full turn; a smaller result means less travel. This is a physical-distance estimate for unaccelerated horizontal input. Measure an actual turn in the game when precision matters, especially if acceleration or additional multipliers are enabled.</p></section>
    <section><h2>How does a sensitivity converter work?</h2><p>For supported games, the converter preserves the same degrees per mouse count. It multiplies the source sensitivity by the source degrees-per-count constant and divides by the target constant. A game is included only when its input scale is backed by a reliable technical or open-source reference. Games without sufficiently confident constants are omitted rather than approximated.</p><h2>Why can converted sensitivity still feel different?</h2><p>Field of view changes apparent motion on screen. Scoped sensitivity, acceleration, frame timing, input smoothing, resolution scaling and the game&apos;s camera implementation can also change perception. A mathematically matched horizontal turn therefore may not feel identical. Use the converted value as a careful starting point, verify it in a safe practice area, and adjust for comfort.</p><p>The calculator runs locally and does not send DPI, sensitivity or selected games through analytics. Results are informational and no setting is saved automatically.</p></section>
  </ToolPageFrame>;
}
