import type { Metadata } from 'next';
import KeyboardTester from '@/components/tools/KeyboardTester';
import ToolPageFrame from '@/components/tools/ToolPageFrame';
import { canonical } from '@/lib/features';

const title = 'Keyboard Tester - Test Every Key Online | GR8 GAMZ';
const description = 'Test keyboard keys online with a visual keyboard, keydown and keyup feedback, pressed-key count and KeyboardEvent code details.';
export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: canonical('/tools/keyboard-tester') }, robots: { index: true, follow: true } };

export default function KeyboardTesterPage() {
  return <ToolPageFrame toolId="keyboard-tester" description={description} eyebrow="Online key test" intro="Focus the test panel and press keys to see what your browser receives. Active keys light up immediately, while tested keys remain marked so you can work across the keyboard without sending the key data anywhere." utility={<KeyboardTester />}>
    <section><h2>How to test every key on your keyboard</h2><p>Start by clicking or tabbing into the keyboard test panel. Press one key at a time and watch the matching visual key change. The tested-key counter tracks unique browser codes, while the detail panel reports the most recent key value, its physical code, location and whether the browser considered it a repeated press. Work systematically from one side of the keyboard to the other, including modifier keys and arrows.</p><p>The visual layout covers the common keys found on many desktop and laptop keyboards. Compact boards, regional layouts and specialist keyboards may contain extra keys that are not drawn. Their event details can still appear in the result panel when the browser reports them. The tester deliberately leaves Tab available so keyboard users can move focus and exit the test normally.</p></section>
    <section><h2>How do I know if a keyboard key is broken?</h2><p>A key that never produces an event after several careful presses may deserve further investigation, but this page cannot prove a hardware failure. First make sure the test area has focus. Then try the key in another browser, a plain text field and another application. Check whether an operating-system shortcut, accessibility feature, remapping utility or game overlay is intercepting it.</p><p>If the same physical key fails consistently in several independent places while nearby keys work, clean and inspect the keyboard according to its manufacturer&apos;s guidance. For a removable keyboard, testing another USB port or wireless connection can help separate a connection issue from the key switch itself. Avoid taking apart equipment unless its documentation says that is safe.</p></section>
    <section><h2>Ghosting and N-key rollover</h2><p>Keyboard ghosting describes unwanted or missing key reports when particular combinations are pressed. Keyboard matrix design can make some simultaneous combinations harder to register than others. To observe a combination here, hold several keys while the panel has focus and check which visual keys remain active. Browser and operating-system handling can still affect what you see.</p><p>N-key rollover, often shortened to NKRO, describes how many simultaneous key presses a keyboard can report independently. The term does not guarantee that every browser, adapter or connection mode exposes the same result. Test the exact combinations you use in a game, such as movement plus a modifier, rather than relying only on a product label.</p></section>
    <section><h2>Why might a key work here but not in a game?</h2><p>This tester displays standard browser keyboard events. A game may listen for a different code, ignore keys reserved by the browser, apply its own bindings or capture input only after its play area receives focus. Check the game&apos;s control menu and reset custom bindings if necessary. Browser extensions, keyboard-layout settings and overlays can also change behaviour.</p><h2>Can I test a laptop keyboard online?</h2><p>Yes. A laptop keyboard normally reports the same browser events as an external keyboard. Function-layer actions for brightness, volume or hardware controls may be handled by the laptop before the browser sees them, so those keys are not reliable candidates for an online test. On a phone or tablet, the on-screen keyboard generally does not expose a full physical-key layout; use this page with a connected hardware keyboard for meaningful results.</p></section>
  </ToolPageFrame>;
}
