const canvas=document.getElementById('c'),ctx=canvas.getContext('2d');
let W=0,H=0,D=1,playing=false,paused=false,ended=false,score=0,best=+localStorage.getItem('best_'+CFG.id)||0,last=0,startT=0,combo=0,maxCombo=0,streak=0,state={},objects=[],particles=[],keys={},pointer={down:false,x:0,y:0,sx:0,sy:0};
const $=id=>document.getElementById(id),scoreEl=$('score'),bestEl=$('best'),timeEl=$('time'),modeEl=$('mode'),overlay=$('overlay'),toast=$('toast');
bestEl.textContent=best;modeEl.textContent=CFG.label||'V20';
function resize(){D=Math.min(2,devicePixelRatio||1);W=Math.max(320,innerWidth);H=Math.max(560,innerHeight);canvas.width=W*D;canvas.height=H*D;ctx.setTransform(D,0,0,D,0,0)}
addEventListener('resize',resize);resize();
$('start').onclick=start;$('how').onclick=()=>{$('help').style.display=$('help').style.display==='none'?'block':'none'};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function add(n,msg){const gain=Math.max(1,Math.round(n));score+=gain;scoreEl.textContent=score;if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('best_'+CFG.id,best)}if(msg)show(msg)}
function show(t){toast.textContent=t;toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show')}
function burst(x,y,color='#35ff8d',count=12){for(let i=0;i<count;i++){let a=Math.random()*7,sp=80+Math.random()*220;particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:.35+Math.random()*.6,r:2+Math.random()*3,color})}}
function postResult(reason){try{parent.postMessage({source:'GR8_GAMZ',type:'score',game:CFG.id,score,best,mode:CFG.label||CFG.mode,streak,combo:maxCombo,survival:Math.floor((performance.now()-startT)/1000),reason},'*')}catch(e){}}
function end(t){if(ended)return;ended=true;playing=false;paused=false;postResult(t);overlay.style.display='grid';overlay.querySelector('h1').textContent=t;overlay.querySelector('p').textContent='Score '+score+' • Best '+best+' • one more premium run?';$('start').textContent='Play again'}
function start(){overlay.style.display='none';score=0;scoreEl.textContent=0;combo=0;maxCombo=0;streak=0;ended=false;playing=true;paused=false;objects=[];particles=[];state={t:0,spawn:.4};startT=last=performance.now();init()}
addEventListener('message',e=>{let d=e.data||{};if(d.source!=='GR8_GAMZ_HOST')return;if(d.type==='pause')paused=true;if(d.type==='resume')paused=false});
addEventListener('keydown',e=>{let k=e.key.toLowerCase();keys[k]=true;if(['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s',' '].includes(k))e.preventDefault();if(e.key===' '&&!playing)start();if(CFG.mode==='ice'&&playing)moveIce(k);if(CFG.mode==='lava'&&playing)moveLava(k)});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.onpointerdown=e=>{pointer={down:true,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY};down(e)};
canvas.onpointermove=e=>{pointer.x=e.clientX;pointer.y=e.clientY;move(e)};
canvas.onpointerup=e=>{pointer.down=false;up(e)};
addEventListener('touchmove',e=>{if(playing)e.preventDefault()},{passive:false});

function init(){
  const m=CFG.mode;
  if(m==='pinball'){state.ball={x:W/2,y:H*.28,r:12,vx:170,vy:180};state.lives=3;state.bumpers=[{x:W*.35,y:H*.34,r:34,c:'#35ff8d'},{x:W*.63,y:H*.37,r:34,c:'#ff2f7d'},{x:W*.5,y:H*.52,r:30,c:'#44eaff'}];state.left=false;state.right=false}
  if(m==='bowling'){state.ball={x:W/2,y:H-95,r:22,vx:0,vy:0,roll:false};resetPins()}
  if(m==='lava'){state.cols=5;state.rows=7;state.p={x:2,y:6};state.goal={x:2,y:0};state.lava=[];for(let i=0;i<7;i++)state.lava.push({x:Math.floor(Math.random()*5),y:i});}
  if(m==='golf'){state.ball={x:W*.22,y:H*.72,r:14,vx:0,vy:0};state.hole={x:W*.78,y:H*.28,r:24};state.shots=0;state.obs=[{x:W*.52,y:H*.5,r:44},{x:W*.65,y:H*.65,r:32}]}
  if(m==='monster'){state.truck={x:140,y:H-118,vy:0,on:true};state.spawn=.3;state.dist=0}
  if(m==='slice'){state.left=60;state.spawn=.2}
  if(m==='ninja'){state.ninja={x:150,y:H-145,vy:0,on:true};state.spawn=.2;state.dist=0}
  if(m==='cannon'){state.targets=[];state.reload=0;state.balls=[];for(let i=0;i<6;i++)spawnCoin()}
  if(m==='ice'){state.cols=6;state.rows=6;state.p={x:0,y:5};state.goal={x:5,y:0};state.blocks=[{x:2,y:5},{x:2,y:4},{x:2,y:2},{x:4,y:3},{x:1,y:1}];state.cracks=[{x:3,y:3},{x:5,y:2}]}
  if(m==='memory'){state.cards=[];state.open=[];let icons=['★','◆','●','▲','✦','✚'];let arr=[...icons,...icons].sort(()=>Math.random()-.5);arr.forEach((v,i)=>state.cards.push({v,open:false,done:false,i}));state.turns=0}
}
function resetPins(){state.pins=[];let sx=W/2,sy=150;for(let r=0;r<4;r++)for(let c=0;c<=r;c++)state.pins.push({x:sx+(c-r/2)*44,y:sy+r*42,hit:false,r:12})}
function spawnCoin(){state.targets.push({x:240+Math.random()*(W-300),y:115+Math.random()*(H*.48),r:18+Math.random()*10,hit:false})}

function update(dt){
  if(paused)return;state.t+=dt;
  const m=CFG.mode;
  if(m==='pinball')updPinball(dt);
  if(m==='bowling')updBowling(dt);
  if(m==='monster')updMonster(dt);
  if(m==='slice')updSlice(dt);
  if(m==='ninja')updNinja(dt);
  if(m==='cannon')updCannon(dt);
  if(m==='golf')updGolf(dt);
  for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);
}
function updPinball(dt){let b=state.ball;b.vy+=120*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r||b.x>W-b.r){b.vx*=-1;b.x=clamp(b.x,b.r,W-b.r)}if(b.y<b.r){b.vy=Math.abs(b.vy)}for(let bu of state.bumpers){let d=Math.hypot(b.x-bu.x,b.y-bu.y);if(d<b.r+bu.r){let a=Math.atan2(b.y-bu.y,b.x-bu.x);b.vx=Math.cos(a)*420;b.vy=Math.sin(a)*420;combo++;maxCombo=Math.max(maxCombo,combo);add(80+combo*10,'BUMPER');burst(bu.x,bu.y,bu.c,16)}}let ly=H-88;if(b.y>ly-20&&b.y<ly+18){if(state.left&&b.x<W*.48){b.vy=-420;b.vx-=180;add(15,'FLIP')}if(state.right&&b.x>W*.52){b.vy=-420;b.vx+=180;add(15,'FLIP')}}if(b.y>H+40){state.lives--;if(state.lives<0)return end('BALL LOST');b.x=W/2;b.y=H*.25;b.vx=170;b.vy=160;combo=0}}
function updBowling(dt){let b=state.ball;if(b.roll){b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=.992;b.vy*=.992;for(let p of state.pins){if(!p.hit&&Math.hypot(b.x-p.x,b.y-p.y)<b.r+p.r){p.hit=true;streak++;add(90+streak*10,'PIN');burst(p.x,p.y,'#fbbf24',12)}}if(Math.abs(b.vy)<12||b.y<80){let hit=state.pins.filter(p=>p.hit).length;if(hit>=10){add(600,'STRIKE');resetPins()}else if(b.y<60||Math.abs(b.vy)<12){end('LANE COMPLETE')}}}}
function updGolf(dt){let b=state.ball;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=.985;b.vy*=.985;if(b.x<b.r||b.x>W-b.r)b.vx*=-1;if(b.y<b.r||b.y>H-b.r)b.vy*=-1;for(let o of state.obs){let d=Math.hypot(b.x-o.x,b.y-o.y);if(d<b.r+o.r){let a=Math.atan2(b.y-o.y,b.x-o.x);b.vx=Math.cos(a)*260;b.vy=Math.sin(a)*260;burst(o.x,o.y,'#ff2f7d',8)}}if(Math.hypot(b.x-state.hole.x,b.y-state.hole.y)<state.hole.r){add(Math.max(1000-state.shots*120,300),'HOLED');end('PUTT SUNK')}}
function updMonster(dt){let t=state.truck;t.vy+=760*dt;t.y+=t.vy*dt;if(t.y>H-118){t.y=H-118;t.vy=0;t.on=true}state.spawn-=dt;state.dist+=dt*10;if(state.spawn<=0){state.spawn=.78;objects.push({x:W+80,y:H-100,w:34+Math.random()*36,h:38,type:Math.random()<.7?'crate':'ramp'})}for(let o of objects){o.x-=280*dt;if(o.x<150&&o.x+o.w>105&&Math.abs(t.y-(H-118))<8){if(o.type==='crate'){add(90,'CRUSH');burst(o.x,o.y,'#fbbf24',10);o.dead=true}else if(t.y>H-130)return end('TRUCK CRASH')}if(o.x<-100){o.dead=true;add(20)}}objects=objects.filter(o=>!o.dead)}
function updSlice(dt){state.left-=dt;if(state.left<=0)return end('TIME UP');timeEl.textContent=Math.ceil(state.left)+'s';state.spawn-=dt;if(state.spawn<=0){state.spawn=.42;objects.push({x:70+Math.random()*(W-140),y:H+40,vx:-80+Math.random()*160,vy:-(360+Math.random()*220),r:20+Math.random()*14,type:Math.random()<.16?'bomb':'fruit',sliced:false})}for(let o of objects){o.vy+=520*dt;o.x+=o.vx*dt;o.y+=o.vy*dt;if(o.y>H+80)o.dead=true}objects=objects.filter(o=>!o.dead)}
function updNinja(dt){let n=state.ninja;n.vy+=860*dt;n.y+=n.vy*dt;if(n.y>H-145){n.y=H-145;n.vy=0;n.on=true}state.spawn-=dt;state.dist+=dt*10;if(state.spawn<=0){state.spawn=.72;objects.push({x:W+40,y:H-105,type:Math.random()<.72?'spike':'orb'})}for(let o of objects){o.x-=310*dt;if(o.type==='spike'&&Math.abs(o.x-n.x)<34&&n.y>H-178)return end('SPIKE HIT');if(o.type==='orb'&&Math.abs(o.x-n.x)<38&&Math.abs(o.y-n.y)<50){o.dead=true;add(120,'ORB');burst(o.x,o.y,'#35ff8d',12)}if(o.x<-80){o.dead=true;if(o.type==='spike')add(35)}}objects=objects.filter(o=>!o.dead)}
function updCannon(dt){for(let b of state.balls){b.vy+=380*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<0||b.x>W)b.vx*=-1;for(let t of state.targets){if(!t.hit&&Math.hypot(b.x-t.x,b.y-t.y)<b.r+t.r){t.hit=true;combo++;maxCombo=Math.max(maxCombo,combo);add(130+combo*25,'COIN');burst(t.x,t.y,'#fbbf24',16)}}if(b.y>H+40)b.dead=true}state.balls=state.balls.filter(b=>!b.dead);state.targets=state.targets.filter(t=>!t.hit);if(state.targets.length<3)spawnCoin()}
function moveLava(k){let dx=0,dy=0;if(k==='arrowleft'||k==='a')dx=-1;if(k==='arrowright'||k==='d')dx=1;if(k==='arrowup'||k==='w')dy=-1;if(k==='arrowdown'||k==='s')dy=1;if(!dx&&!dy)return;let nx=clamp(state.p.x+dx,0,state.cols-1),ny=clamp(state.p.y+dy,0,state.rows-1);state.p={x:nx,y:ny};if(state.lava.some(l=>l.x===nx&&l.y===ny))return end('LAVA HIT');add(20);if(nx===state.goal.x&&ny===state.goal.y){add(700,'ESCAPE');end('PORTAL FOUND')}}
function moveIce(k){let dx=0,dy=0;if(k==='arrowleft'||k==='a')dx=-1;if(k==='arrowright'||k==='d')dx=1;if(k==='arrowup'||k==='w')dy=-1;if(k==='arrowdown'||k==='s')dy=1;if(!dx&&!dy)return;let x=state.p.x,y=state.p.y;while(true){let nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=state.cols||ny>=state.rows||state.blocks.some(b=>b.x===nx&&b.y===ny))break;x=nx;y=ny;if(state.cracks.some(c=>c.x===x&&c.y===y))return end('ICE CRACKED')}state.p={x,y};add(25);if(x===state.goal.x&&y===state.goal.y){add(800,'SOLVED');end('GOAL REACHED')}}
function down(e){if(!playing)return;if(CFG.mode==='pinball'){state.left=e.clientX<W/2;state.right=e.clientX>=W/2}if(CFG.mode==='memory'){tapMemory(e.clientX,e.clientY)}if(CFG.mode==='lava'){tapGrid(e.clientX,e.clientY,'lava')}if(CFG.mode==='ice'){tapGrid(e.clientX,e.clientY,'ice')}}
function move(e){if(CFG.mode==='slice'&&playing){for(let o of objects){if(!o.sliced&&Math.hypot(o.x-e.clientX,o.y-e.clientY)<o.r+18){if(o.type==='bomb')return end('BOMB HIT');o.sliced=true;o.dead=true;combo++;maxCombo=Math.max(maxCombo,combo);add(95+combo*14,'SLICE');burst(o.x,o.y,'#35ff8d',18)}}}}
function up(e){if(!playing)return;if(CFG.mode==='pinball'){state.left=false;state.right=false}if(CFG.mode==='bowling'&&!state.ball.roll){let b=state.ball,dx=e.clientX-pointer.sx,dy=e.clientY-pointer.sy;if(dy<-20){b.vx=dx*1.7;b.vy=dy*3.1;b.roll=true}}if(CFG.mode==='golf'){let b=state.ball,dx=pointer.sx-e.clientX,dy=pointer.sy-e.clientY;if(Math.hypot(b.vx,b.vy)<20){b.vx=dx*2.6;b.vy=dy*2.6;state.shots++;show('SHOT '+state.shots)}}if(CFG.mode==='monster'){jumpMonster()}if(CFG.mode==='ninja'){jumpNinja()}if(CFG.mode==='cannon'){let dx=pointer.sx-e.clientX,dy=pointer.sy-e.clientY;state.balls.push({x:W/2,y:H-72,r:9,vx:dx*2.4,vy:dy*2.4})}if(CFG.mode==='lava'||CFG.mode==='ice'){let dx=e.clientX-pointer.sx,dy=e.clientY-pointer.sy;if(Math.max(Math.abs(dx),Math.abs(dy))>26){let key=Math.abs(dx)>Math.abs(dy)?(dx>0?'arrowright':'arrowleft'):(dy>0?'arrowdown':'arrowup');CFG.mode==='lava'?moveLava(key):moveIce(key)}}}
function jumpMonster(){let t=state.truck;if(t.on){t.vy=-520;t.on=false;add(10,'JUMP')}}
function jumpNinja(){let n=state.ninja;if(n.on){n.vy=-560;n.on=false;add(10,'LEAP')}}
function tapGrid(x,y,type){let g=gridGeom(type==='lava'?state.cols:state.cols,type==='lava'?state.rows:state.rows);let gx=Math.floor((x-g.ox)/g.s),gy=Math.floor((y-g.oy)/g.s);if(type==='lava'&&Math.abs(gx-state.p.x)+Math.abs(gy-state.p.y)===1){let key=gx<state.p.x?'arrowleft':gx>state.p.x?'arrowright':gy<state.p.y?'arrowup':'arrowdown';moveLava(key)}}
function tapMemory(x,y){let g=gridGeom(4,3),gx=Math.floor((x-g.ox)/g.s),gy=Math.floor((y-g.oy)/g.s),i=gy*4+gx,c=state.cards[i];if(!c||c.done||c.open||state.open.length>=2)return;c.open=true;state.open.push(c);if(state.open.length===2){state.turns++;let [a,b]=state.open;if(a.v===b.v){a.done=b.done=true;state.open=[];streak++;add(160+streak*30,'MATCH');burst(x,y,'#35ff8d',16);if(state.cards.every(c=>c.done))end('PERFECT MEMORY')}else setTimeout(()=>{a.open=b.open=false;state.open=[];streak=0},650)}}
function gridGeom(cols,rows){let s=Math.min(W*.78/cols,H*.62/rows),ox=W/2-s*cols/2,oy=H*.16;return{s,ox,oy}}
function bg(){ctx.fillStyle='#050507';ctx.fillRect(0,0,W,H);let g=ctx.createRadialGradient(W*.5,H*.36,20,W*.5,H*.4,Math.max(W,H));g.addColorStop(0,'rgba(68,234,255,.16)');g.addColorStop(.5,'rgba(53,255,141,.08)');g.addColorStop(1,'rgba(255,47,125,.08)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(53,255,141,.2)';for(let x=0;x<W;x+=44){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(W/2,H*.54);ctx.stroke()}for(let y=H*.48;y<H;y+=34){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function glow(x,y,r,c){let g=ctx.createRadialGradient(x,y,0,x,y,r*3);g.addColorStop(0,c);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r*3,0,7);ctx.fill();ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill()}
function rr(x,y,w,h,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function draw(){bg();if(!playing){ctx.globalAlpha=.16;ctx.fillStyle='#35ff8d';ctx.font='900 92px Arial';ctx.textAlign='center';ctx.fillText(CFG.name,W/2,H/2);ctx.globalAlpha=1;return}let m=CFG.mode;if(m==='pinball')drawPinball();if(m==='bowling')drawBowling();if(m==='lava')drawLava();if(m==='golf')drawGolf();if(m==='monster')drawMonster();if(m==='slice')drawSlice();if(m==='ninja')drawNinja();if(m==='cannon')drawCannon();if(m==='ice')drawIce();if(m==='memory')drawMemory();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);glow(p.x,p.y,p.r,p.color);ctx.globalAlpha=1}if(paused){ctx.fillStyle='rgba(0,0,0,.52)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#35ff8d';ctx.font='900 54px Arial';ctx.textAlign='center';ctx.fillText('PAUSED',W/2,H/2)}}
function drawPinball(){let b=state.ball;ctx.strokeStyle='#35ff8d';ctx.lineWidth=5;ctx.strokeRect(W*.22,60,W*.56,H-130);state.bumpers.forEach(o=>glow(o.x,o.y,o.r,o.c));glow(b.x,b.y,b.r,'#fff');ctx.fillStyle=state.left?'#35ff8d':'#44eaff';ctx.fillRect(W*.3,H-90,120,16);ctx.fillStyle=state.right?'#35ff8d':'#ff2f7d';ctx.fillRect(W*.6,H-90,120,16)}
function drawBowling(){ctx.strokeStyle='#44eaff';ctx.lineWidth=4;ctx.strokeRect(W*.28,60,W*.44,H-105);state.pins.forEach(p=>{if(!p.hit)glow(p.x,p.y,p.r,'#f8fafc')});glow(state.ball.x,state.ball.y,state.ball.r,'#35ff8d');if(pointer.down&&!state.ball.roll){ctx.strokeStyle='#ff2f7d';ctx.beginPath();ctx.moveTo(state.ball.x,state.ball.y);ctx.lineTo(pointer.x,pointer.y);ctx.stroke()}}
function drawLava(){drawTileGrid(state.cols,state.rows,(x,y)=>state.lava.some(l=>l.x===x&&l.y===y)?'#ff2f7d':(state.goal.x===x&&state.goal.y===y?'#35ff8d':'rgba(68,234,255,.22)'));drawPawn(state.p,'#fbbf24',state.cols,state.rows)}
function drawGolf(){glow(state.hole.x,state.hole.y,state.hole.r,'#35ff8d');state.obs.forEach(o=>glow(o.x,o.y,o.r,'#ff2f7d'));glow(state.ball.x,state.ball.y,state.ball.r,'#fff');if(pointer.down&&Math.hypot(state.ball.vx,state.ball.vy)<20){ctx.strokeStyle='#fbbf24';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(state.ball.x,state.ball.y);ctx.lineTo(pointer.x,pointer.y);ctx.stroke()}}
function drawMonster(){ctx.strokeStyle='#35ff8d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,H-90);ctx.lineTo(W,H-90);ctx.stroke();rr(105,state.truck.y-28,84,42,12,'#35ff8d');glow(124,state.truck.y+20,15,'#050507');glow(172,state.truck.y+20,15,'#050507');objects.forEach(o=>rr(o.x,o.y,o.w,o.h,8,o.type==='crate'?'#fbbf24':'#ff2f7d'))}
function drawSlice(){objects.forEach(o=>glow(o.x,o.y,o.r,o.type==='bomb'?'#ff2f7d':'#35ff8d'))}
function drawNinja(){ctx.strokeStyle='#35ff8d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,H-105);ctx.lineTo(W,H-105);ctx.stroke();glow(state.ninja.x,state.ninja.y,24,'#44eaff');objects.forEach(o=>{if(o.type==='spike'){ctx.fillStyle='#ff2f7d';ctx.beginPath();ctx.moveTo(o.x,o.y-34);ctx.lineTo(o.x-24,o.y+28);ctx.lineTo(o.x+24,o.y+28);ctx.fill()}else glow(o.x,o.y,16,'#35ff8d')})}
function drawCannon(){ctx.fillStyle='#35ff8d';ctx.fillRect(W/2-35,H-74,70,30);state.targets.forEach(t=>glow(t.x,t.y,t.r,'#fbbf24'));state.balls.forEach(b=>glow(b.x,b.y,b.r,'#44eaff'));if(pointer.down){ctx.strokeStyle='#ff2f7d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(W/2,H-72);ctx.lineTo(pointer.x,pointer.y);ctx.stroke()}}
function drawIce(){drawTileGrid(state.cols,state.rows,(x,y)=>state.blocks.some(b=>b.x===x&&b.y===y)?'#111827':state.cracks.some(c=>c.x===x&&c.y===y)?'#ff2f7d':(state.goal.x===x&&state.goal.y===y?'#35ff8d':'rgba(68,234,255,.22)'));drawPawn(state.p,'#44eaff',state.cols,state.rows)}
function drawMemory(){let g=gridGeom(4,3);state.cards.forEach((c,i)=>{let x=g.ox+(i%4)*g.s,y=g.oy+Math.floor(i/4)*g.s;rr(x+8,y+8,g.s-16,g.s-16,16,c.done?'rgba(53,255,141,.25)':(c.open?'#35ff8d':'rgba(68,234,255,.22)'));if(c.open||c.done){ctx.fillStyle=c.done?'#35ff8d':'#050507';ctx.font='900 32px Arial';ctx.textAlign='center';ctx.fillText(c.v,x+g.s/2,y+g.s/2+10)}})}
function drawTileGrid(cols,rows,colorFn){let g=gridGeom(cols,rows);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)rr(g.ox+x*g.s+5,g.oy+y*g.s+5,g.s-10,g.s-10,12,colorFn(x,y))}
function drawPawn(p,color,cols,rows){let g=gridGeom(cols,rows);glow(g.ox+p.x*g.s+g.s/2,g.oy+p.y*g.s+g.s/2,g.s*.22,color)}
function loop(t){let dt=Math.min(.033,(t-last)/1000||.016);last=t;if(playing&&!paused){timeEl.textContent=CFG.mode==='slice'?Math.ceil(state.left||60)+'s':Math.floor((t-startT)/1000)+'s';update(dt)}draw();requestAnimationFrame(loop)}
requestAnimationFrame(loop);
